# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24c8b2213047fc346f96bfc33deed118eb5d8b5a427cb422cbe0a853302cf88fbe83e5120179c33f9dc3c7440a206a43ae2e8aeacf848ecd73db77ad924685ff

test:
  secret_key_base: 3ead89d75b6a33c57e83d69795a8f3a5de7b74213b5e9e03f1f44e3ff15d38d2104c199f31bfe09b19f0afc2af16fa162df19b9005ad439dd48699d7d3dabdc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
